version: "3.8"

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5433"

  web:
    build: .
    command: >
      bash -c "
             python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             gunicorn --reload -b 0.0.0.0:8000 config.wsgi --workers 1 --timeout 300 --log-level DEBUG
           "
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
